# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the workflow will run
on:
  # Запуск только при публиковании нового релиза
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

#      # Runs commands for setup environment
      - name: Prepare environment
        run: | 
          docker-compose --version
          docker --version

      - name: Run docker-compose
        run: make dev_deps

      - name: Get depncecies
        run: make build

      - name: Run linter
        run: make lint

      - name: Run memtx tests
        run: make test_memtx

      - name: Run vinyl tests
        run: make test_vinyl

      - name: Upload rocks
        uses: actions/upload-artifact@v2
        with:
          name: rocks
          path: .rocks
          retention-days: 1

  build:
    # Если тесты были пройдены успешно
    needs: [tests]
    runs-on: [ubuntu-latest]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Download math result for job 1
        uses: actions/download-artifact@v2
        with:
          name: rocks

      - name: Run docker-compose
        run: make dev_deps

      - name: Build RPM packet
        run: make release

      - name: Upload math result for job 1
        uses: actions/upload-artifact@v2
        with:
          name: rpm_packet
          path: memstorage*.rpm
